#!/usr/bin/env bash
# Deploy DynamicLPFeesHook + mock oracle on Base Sepolia, seed liquidity, write frontend/.env.local
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RPC="${RPC:-https://sepolia.base.org}"
KEY="${PRIVATE_KEY:?Set PRIVATE_KEY to your Base Sepolia deployer key}"
WETH="0x4200000000000000000000000000000000000006"
USDC="0x036CbD53842c5426634e7929541eC2318f3dCF7e"

cd "$ROOT"

echo "==> Deploying hook + mock Chainlink feeds on Base Sepolia..."
ORACLE_PRICE8=$(cast call 0x71041dddad3595F9CEd3DcCFBe3D1F4b0a16Bb70 \
  "latestRoundData()(uint80,int256,uint256,uint256,uint80)" --rpc-url https://mainnet.base.org | awk 'NR==2 {print $1}')
echo "    Mainnet Chainlink ETH/USD: $((ORACLE_PRICE8 / 100000000)) USD"
DEPLOY_OUT=$(ORACLE_PRICE8="$ORACLE_PRICE8" forge script script/DeployBaseSepolia.s.sol:DeployBaseSepolia \
  --rpc-url "$RPC" --broadcast --private-key "$KEY" 2>&1)

HOOK=$(echo "$DEPLOY_OUT" | grep -oP 'DynamicLPFeesHook: \K0x[a-fA-F0-9]{40}' | head -1)
POOL=$(echo "$DEPLOY_OUT" | grep -oP 'POOL_ID: \K0x[a-fA-F0-9]{64}' | head -1)
FEED=$(echo "$DEPLOY_OUT" | grep -oP 'Mock ETH/USD feed: \K0x[a-fA-F0-9]{40}' | head -1)

if [ -z "$HOOK" ] || [ -z "$POOL" ]; then
  echo "$DEPLOY_OUT"
  echo "Deploy failed — check PRIVATE_KEY has Base Sepolia ETH"
  exit 1
fi

echo "    Hook:  $HOOK"
echo "    Pool:  $POOL"
echo "    Oracle mock: $FEED"

echo "==> Wrapping ETH for WETH (needs ~1 ETH on deployer)..."
cast send "$WETH" "deposit()" --value 1ether --private-key "$KEY" --rpc-url "$RPC" >/dev/null || true

echo "==> Seeding liquidity (deployer needs USDC — get from Circle faucet)..."
SEED_OUT=$(USE_SEPOLIA=true HOOK_ADDR="$HOOK" ORACLE_PRICE8="$ORACLE_PRICE8" forge script script/SeedLiquidity.s.sol:SeedLiquidity \
  --rpc-url "$RPC" --broadcast --private-key "$KEY" 2>&1) || {
  echo "$SEED_OUT"
  echo "Seed failed — fund deployer with USDC (https://faucet.circle.com) and re-run:"
  echo "  USE_SEPOLIA=true HOOK_ADDR=$HOOK forge script script/SeedLiquidity.s.sol --rpc-url $RPC --broadcast --private-key \$PRIVATE_KEY"
  exit 1
}

ROUTER=$(echo "$SEED_OUT" | grep -oP 'PoolSwapTest \(swap router\): \K0x[a-fA-F0-9]{40}' | head -1)
TICK_LO=$(echo "$SEED_OUT" | grep -oP 'Tick lower: \K-?[0-9]+' | head -1)
TICK_HI=$(echo "$SEED_OUT" | grep -oP 'Tick upper: \K-?[0-9]+' | head -1)

ENV_FILE="$ROOT/frontend/.env.local"
cat > "$ENV_FILE" <<EOF
# Auto-generated by script/setup-sepolia.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
VITE_CHAIN_ID=84532
VITE_HOOK_ADDRESS=$HOOK
VITE_POOL_ID=$POOL
VITE_BASE_RPC_URL=$RPC
VITE_ETH_USD_FEED=$FEED
VITE_POOL_MANAGER=0x05E73354cFDd6745C338b50BcFDfA3Aa6fA03408
VITE_SWAP_ROUTER=$ROUTER
VITE_DEV_PRIVATE_KEY=$KEY
VITE_LP_TICK_LOWER=$TICK_LO
VITE_LP_TICK_UPPER=$TICK_HI
EOF

echo "==> Wrote $ENV_FILE"
echo "==> Start frontend: cd frontend && npm run dev"
