#!/usr/bin/env bash
# One-shot Base mainnet fork setup: anvil + deploy hook + seed liquidity + write frontend/.env.local
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RPC="${RPC:-http://127.0.0.1:8545}"
KEY="${KEY:-0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}"
DEV="${DEV:-0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266}"
WETH="0x4200000000000000000000000000000000000006"
USDC="0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
ANVIL_PORT="${ANVIL_PORT:-8545}"

echo "==> Starting anvil (Base fork) on port $ANVIL_PORT..."
pkill -f "anvil --fork-url" 2>/dev/null || true
sleep 1
setsid nohup anvil --fork-url https://mainnet.base.org --chain-id 8453 --host 127.0.0.1 --port "$ANVIL_PORT" \
  > /tmp/anvil.log 2>&1 < /dev/null &
sleep 8
cast block-number --rpc-url "$RPC" >/dev/null || { echo "Anvil failed to start"; exit 1; }

echo "==> Syncing block timestamp with Chainlink oracle (prevents StaleOraclePrice)..."
ORACLE="0x71041dddad3595F9CEd3DcCFBe3D1F4b0a16Bb70"
UPDATED_AT=$(cast call "$ORACLE" "latestRoundData()(uint80,int256,uint256,uint256,uint80)" --rpc-url "$RPC" | awk 'NR==4 {print $1}')
cast rpc anvil_setNextBlockTimestamp $((UPDATED_AT + 120)) --rpc-url "$RPC" >/dev/null
cast rpc anvil_mine --rpc-url "$RPC" >/dev/null

echo "==> Funding dev account (WETH wrap + USDC)..."
cast send "$WETH" "deposit()" --value 250ether --private-key "$KEY" --rpc-url "$RPC" >/dev/null
SLOT=$(cast index address "$DEV" 9)
cast rpc anvil_setStorageAt "$USDC" "$SLOT" "$(cast to-uint256 8000000000000)" --rpc-url "$RPC" >/dev/null

echo "==> Deploying DynamicLPFeesHook + initializing pool..."
cd "$ROOT"
DEPLOY_OUT=$(forge script script/DeployDynamicLPFeesHook.s.sol:DeployDynamicLPFeesHook \
  --rpc-url "$RPC" --broadcast --private-key "$KEY" 2>&1)
HOOK=$(echo "$DEPLOY_OUT" | grep -oP 'hookAddress: address \K0x[a-fA-F0-9]{40}' | head -1)
POOL=$(echo "$DEPLOY_OUT" | grep -oP 'poolId: bytes32 \K0x[a-fA-F0-9]{64}' | head -1)
echo "    Hook:  $HOOK"
echo "    Pool:  $POOL"

echo "==> Seeding deep concentrated liquidity..."
SEED_OUT=$(HOOK_ADDR="$HOOK" forge script script/SeedLiquidity.s.sol:SeedLiquidity \
  --rpc-url "$RPC" --broadcast --private-key "$KEY" 2>&1)
ROUTER=$(echo "$SEED_OUT" | grep -oP 'PoolSwapTest \(swap router\): \K0x[a-fA-F0-9]{40}' | head -1)
TICK_LO=$(echo "$SEED_OUT" | grep -oP 'Tick lower: \K-?[0-9]+' | head -1)
TICK_HI=$(echo "$SEED_OUT" | grep -oP 'Tick upper: \K-?[0-9]+' | head -1)
echo "    Router: $ROUTER"
echo "    Ticks:  [$TICK_LO, $TICK_HI]"

echo "==> Verifying previewFee..."
FEE=$(cast call "$HOOK" "previewFee(bytes32)(uint24,uint256)" "$POOL" --rpc-url "$RPC")
echo "    previewFee: $FEE"

ENV_FILE="$ROOT/frontend/.env.local"
cat > "$ENV_FILE" <<EOF
# Auto-generated by script/setup-fork.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
VITE_HOOK_ADDRESS=$HOOK
VITE_POOL_ID=$POOL
VITE_BASE_RPC_URL=$RPC
VITE_SWAP_ROUTER=$ROUTER
VITE_DEV_PRIVATE_KEY=$KEY
VITE_LP_TICK_LOWER=$TICK_LO
VITE_LP_TICK_UPPER=$TICK_HI
EOF

echo "==> Wrote $ENV_FILE"
echo "==> Done. Restart vite (npm run dev) if it was already running."
